# Generated by Django 5.0 on 2023-12-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_courses_view_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='view_more',
        ),
    ]
