# Generated by Django 5.0 on 2023-12-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_courses_view_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='banner_image',
            field=models.ImageField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='content',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='content_head',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='content_imga',
            field=models.ImageField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
    ]
