# Generated by Django 5.0 on 2023-12-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_courses_banner_image_courses_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='content_imga',
        ),
        migrations.AddField(
            model_name='courses',
            name='content_image',
            field=models.ImageField(default='img', upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='banner_image',
            field=models.ImageField(default='img', upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='content',
            field=models.CharField(default='content', max_length=1000),
        ),
        migrations.AlterField(
            model_name='courses',
            name='content_head',
            field=models.CharField(default='heading', max_length=100),
        ),
    ]
