# Generated by Django 5.0 on 2023-12-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_courses_content_imga_courses_content_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='content2',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AddField(
            model_name='courses',
            name='content_head2',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='courses',
            name='content_image2',
            field=models.ImageField(default='none', upload_to='image/'),
        ),
    ]
