# Generated by Django 4.2.8 on 2024-01-24 12:24

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maclloc',
            name='mobile',
            field=models.IntegerField(validators=[polls.models.error]),
        ),
    ]
